#ifndef ISFDoc_hpp
#define ISFDoc_hpp

#include <vector>
#include "VVISF_Base.hpp"
#include "ISFAttr.hpp"




namespace VVISF
{




using namespace std;

class ISFScene;




/*!
\ingroup VVISF_BASIC
\brief Describes an "ISF file"- requires an actual file on disk which is parsed.  Capable of generating GLSL source code for the various shader types.

Constructing an instance of this class will load the files from disk into local string vars, parse them, and populate the instance with all the attributes(ISFAttr)/passes(ISFPassTarget) necessary to fully describe the ISF file.

Notes on use:
- ISFDoc's constructor will throw an ISFErr if the file cannot be opened, or if there's a problem parsing the JSON blob in the ISF file.
- ISFDoc can be used to examine the properties of "ISF files" on disk- create an ISFDoc instance, passing the constructor the path of the file to load, and then then you can examing the properties of the doc to get info about the ISF file.
- Internally, ISFDoc has all the plumbing necessary to be used to render the ISF file- when you tell an ISFScene to use a file, it's actually creating an ISFDoc which is used to store information necessary for rendering- both ISFAttr and ISFPassTarget cache GL resources and interact directly with GL to do things like set uniform values, calculate rendering resolutions by evaluating strings and substituting variables, and things like that.  Even the GLSL source code ISFScene compiles and runs for its GL programs is generated by the ISFDoc.
*/
class VVISF_EXPORT ISFDoc	{
	private:
		recursive_mutex		propLock;
		
		string			*path = nullptr;	//	full path to the loaded file
		string			*name = nullptr;	//	just the file name (including its extension)
		string			*description = nullptr;	//	description of whatever the file does
		string			*credit = nullptr;	//	credit
		string			*vsn = nullptr;
		ISFFileType		type = ISFFileType_Source;
		
		vector<string>			categories;	//	array of strings of the category names this doc should be listed under
		vector<ISFAttrRef>	inputs;	//	array of ISFAttrRef instances for the various inputs
		vector<ISFAttrRef>	imageInputs;	//	array of ISFAttrRef instances for the image inputs (the image inputs are stored in two arrays).
		vector<ISFAttrRef>	audioInputs;	//	array of ISFAttrRef instances for the audio inputs
		vector<ISFAttrRef>	imageImports;	//	array of ISFAttrRef instances that describe imported images. attrib's 'attribName' is the name of the sampler, attrib's 'description' is the path to the file.
		
		//bool					bufferRequiresEval = false;	//	NO by default, set to YES during file open if any of the buffers require evaluation (faster than checking every single buffer every pass)
		vector<ISFPassTargetRef>	persistentBuffers;
		vector<ISFPassTargetRef>	tempBuffers;
		vector<string>			renderPasses;
		
		string			*jsonSourceString = nullptr;	//	the JSON string from the source *including the comments and any linebreaks before/after it*
		string			*jsonString = nullptr;	//	the JSON string copied from the source- doesn't include any comments before/after it
		string			*vertShaderSource = nullptr;	//	the raw vert shader source before being find-and-replaced
		string			*fragShaderSource = nullptr;	//	the raw frag shader source before being find-and-replaced
		
		ISFScene		*parentScene = nullptr;	//	nil by default, weak ref to the scene that "owns" me.  only non-nil when an ISFScene is using the doc to render.
		
	public:
		
		/*!
		\name Constructors
		*/
		///@{
		
		//! Constructs an ISFDoc instance from a passed file on disk.  Consider using CreateISFDocRef() instead.
		/*!
		\param inPath The path to the ISF file you want to load as an ISFDoc.
		\param inParentScene The scene that will be used to render this ISFDoc, or null if no scene is to be used.
		Throws an ISFErr if there is a problem of some sort loading the ISF file from disk or parsing the JSON in the ISF file.
		*/
		ISFDoc(const string & inPath, ISFScene * inParentScene=nullptr) throw(ISFErr);
		
		//! Constructs an ISFDoc instance from shader strings.  Consider using CreateISFDocRef() instead.
		/*
		\param inFSContents A string containing the fragment shader portion of the ISF file.  The JSON blob that defines the ISF file must be contained in here.
		\param inVSContents A string containing the vertex shader portion of the ISF file.  If you don't have a vertex shader to pass, VVISF defines a static string "ISFVertPassthru_GL2", which should work as a "passthru" vertex shader for most purposes.
		\param inParentScene The scene that will be used to render this ISFDoc, or null if no scene is to be used.
		Throws an ISFErr if there is a problem of some sort parsing the JSON blob from the frag shader string.
		*/
		ISFDoc(const string & inFSContents, const string & inVSContents, ISFScene * inParentScene=nullptr);
		
		///@}
		
		
		~ISFDoc();
		
		
		/*!
		\name ISF file properties
		*/
		///@{
		
		//!	Returns the path of the ISF file for the receiver.  This is probably the path to the frag shader.
		string getPath() const { return (path==nullptr) ? string("") : string(*path); }
		//!	Returns the name of the receiver's ISF file (the file name, minus the extension).
		string getName() const { return (name==nullptr) ? string("") : string(*name); }
		//!	Returns the receiver's "description" string, as defined in its JSON blob ("DESCRIPTION").
		string getDescription() const { return (description==nullptr) ? string("") : string(*description); }
		//!	Returns the receiver's "credit" string, as defined in its JSON blob ("CREDIT").
		string getCredit() const { return (credit==nullptr) ? string("") : string(*credit); }
		//!	Returns the receiver's "vsn" string, as defined in its JSON blob ("VSN")
		string getVsn() const { return (vsn==nullptr) ? string("") : string(*vsn); }
		//!	Returns the receiver's file type.
		ISFFileType getType() const { return type; }
		//!	Returns a vector containing strings listing the receiver's categories.
		vector<string> & getCategories() { return categories; }
		
		///@}
		
		
		/*!
		\name ISF attribute/INPUT getters
		*/
		///@{
		
		//!	Returns a vector of ISFAttrRef instances describing all of the receiver's inputs.
		vector<ISFAttrRef> & getInputs() { return inputs; }
		//!	Returns a vector of ISFAttrRef instances describing only the receiver's image inputs.
		vector<ISFAttrRef> & getImageInputs() { return imageInputs; }
		//!	Returns a vector of ISFAttrRef instances describing only the receiver's audio inputs.
		vector<ISFAttrRef> & getAudioInputs() { return audioInputs; }
		//!	Returns a vector of ISFAttrRef instances describing only the receiver's audioFFT inputs.
		vector<ISFAttrRef> & getImageImports() { return imageImports; }
		//!	Returns a vector of ISFAttrRef instances describing only the receiver's inputs that match the passed type.
		vector<ISFAttrRef> getInputsOfType(const ISFValType & inInputType);
		//!	Returns the ISFAttrRef for the input with the passed name
		ISFAttrRef getInput(const string & inAttrName);
		
		///@}
		
		
		/*!
		\name ISF render pass getters
		*/
		///@{
		
		//!	Returns a vector of ISFPassTargetRef instances describing every pass that has a persistent buffer.
		vector<ISFPassTargetRef> getPersistentBuffers() const { return persistentBuffers; }
		//!	Returns a vector of ISFPassTargetRef instances describing every pass that doesn't have a persistent buffer.
		vector<ISFPassTargetRef> getTempBuffers() const { return tempBuffers; }
		//!	Returns a vector of std::string instances describing the names of the render passes, in order.  If the names were not specified properly in the JSON blob, this array will be incomplete or inaccurate and rendering won't work!
		vector<string> & getRenderPasses() { return renderPasses; }
		//!	Returns the GLBufferRef for the passed key.  Checks all attributes/inputs as well as persistent and temp buffers.
		const GLBufferRef getBufferForKey(const string & n);
		//!	Returns the persistent buffer for the render pass with the passed key.
		const GLBufferRef getPersistentBufferForKey(const string & n);
		//!	Returns the temp buffer for the render pass with the passed key.
		const GLBufferRef getTempBufferForKey(const string & n);
		//!	Returns the ISFPassTarget that matches the passed key.  Returns null if no pass could be found.
		const ISFPassTargetRef getPassTargetForKey(const string & n);
		//!	Returns the ISFPassTarget that matches the passed key.  Returns null if no pass could be found or if the pass found wasn't flagged as requiring a persistent buffer.
		const ISFPassTargetRef getPersistentPassTargetForKey(const string & n);
		//!	Returns the ISFPassTarget that matches the passed key.  Returns null if no pass could be found or if the pass found was flagged as requiring a persistent buffer.
		const ISFPassTargetRef getTempPassTargetForKey(const string & n);
		
		///@}
		
		
		/*!
		\name ISF file source code getters
		*/
		///@{
		
		//! Returns the JSON string from the source *including the comments and any linebreaks before/after it*
		string * getJSONSourceString() const { return jsonSourceString; }
		//!	Returns the JSON string copied from the source- doesn't include any comments before/after it
		string * getJSONString() const { return jsonString; }
		//!	Returns the raw vert shader source before being find-and-replaced
		string * getVertShaderSource() const { return vertShaderSource; }
		//!	Returns the raw frag shader source before being find-and-replaced
		string * getFragShaderSource() const { return fragShaderSource; }
		//!	Populates the passed var with the JSON string from the source *including the comments and any linebreaks before/after it*
		void getJSONSourceString(string & outStr);
		//!	Populates the passed var with the JSON string copied from the source- doesn't include any comments before/after it
		void getJSONString(string & outStr);
		//!	Populates the passed var with the raw vert shader source before being find-and-replaced.
		void getVertShaderSource(string & outStr);
		//!	Populates the passed var with the raw frag shader source before being find-and-replaced
		void getFragShaderSource(string & outStr);
		
		///@}
		
		void setParentScene(ISFScene * n) { parentScene=n; }
		ISFScene * getParentScene() { return parentScene; }
		
		//	returns a string describing the type of the expected texture samplers ("2" for 2D, "R" for Rect, "C" for Cube).  save this, if it changes in a later pass the shader source must be generated again.
		string generateTextureTypeString();
		/*!
		\brief Returns a true if successful.  Generates GLSL source code, populating the provided vars with strings that are usable for frag/vert shaders
		\param outFragSrc A non-null pre-allocated std::string variable which will be populated with the fragment shader source code generated for this ISF file.
		\param outVertSrc A non-null pre-allocated std::string variable which will be populated with the vertex shader source code generated for this ISF file.
		\param inGLVers The version of OpenGL that the generated source code must be compatible with.
		\param inVarsAsUBO Defaults to false.  If true, variable declarations for non-image INPUTS will be assembled in a uniform block.  This option was added because a downstream utility requires it.
		*/
		bool generateShaderSource(string * outFragSrc, string * outVertSrc, VVGL::GLVersion & inGLVers, const bool & inVarsAsUBO=false);
		//	this method must be called before rendering (passes/etc may have expressions that require the render dims to be evaluated)
		void evalBufferDimensionsWithRenderSize(const VVGL::Size & inSize);
		
		VVISF_EXPORT friend ostream & operator<<(ostream & os, const ISFDoc & n);
		
	protected:
		//	used so we can have two constructors without duplicating code
		void _initWithRawFragShaderString(const string & inRawFile);
		//	returns a true if successful.  populates a string with variable declarations for a frag shader
		bool _assembleShaderSource_VarDeclarations(string * outVSString, string * outFSString, VVGL::GLVersion & inGLVers, const bool & inVarsAsUBO=false);
		//	returns a true if successful.  populates a map with string/value pairs that will be used to evaluate variable names in strings
		bool _assembleSubstitutionMap(map<string,double*> * outMap);
};




//! Constructs an ISFDoc instance from a passed file on disk.
/*!
\relatedalso ISFDoc
\param inPath The path to the ISF file you want to load as an ISFDoc.
\param inParentScene The scene that will be used to render this ISFDoc, or null if no scene is to be used.
Throws an ISFErr if there is a problem of some sort loading the ISF file from disk or parsing the JSON in the ISF file.
*/
inline ISFDocRef CreateISFDocRef(const string & inPath, ISFScene * inParentScene=nullptr) throw(ISFErr) { return make_shared<ISFDoc>(inPath,inParentScene); }

//! Constructs an ISFDoc instance from shader strings.
/*!
\relatedalso ISFDoc
\param inFSContents A string containing the fragment shader portion of the ISF file.  The JSON blob that defines the ISF file must be contained in here.
\param inVSContents A string containing the vertex shader portion of the ISF file.  If you don't have a vertex shader to pass, VVISF defines a static string "ISFVertPassthru_GL2", which should work as a "passthru" vertex shader for most purposes.
\param inParentScene The scene that will be used to render this ISFDoc, or null if no scene is to be used.
Throws an ISFErr if there is a problem of some sort parsing the JSON blob from the frag shader string.
*/
inline ISFDocRef CreateISFDocRef(const string & inFSContents, const string & inVSContents, ISFScene * inParentScene=nullptr) { return make_shared<ISFDoc>(inFSContents,inVSContents,inParentScene); }



}




#endif /* ISFDoc_hpp */
